name: Web Build and Deploy With Emscripten

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  actions: write
  deployments: write
  pages: write
  contents: write
  attestations: write
  checks: write
  discussions: write
  id-token: write
  packages: write
  security-events: write
  statuses: write

on:
  release:
    types:
      - created
  workflow_dispatch:
    
  
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.61

    - name: Configure CMake with Emscripten
      run: emcmake cmake -B build -D ASSIMP_BUILD_ZLIB=ON

    - name: Build
      run: cmake --build build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: web
        path: build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/examples